# Generated by Django 4.2.22 on 2025-06-07 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizhubapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('global', 'Global'), ('category', 'Category'), ('quiz', 'Quiz Specific'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizhubapi.category')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizhubapi.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='answers/audio/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/images/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='media_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='answer',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='answers/videos/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='questions/audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='media_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='questions/videos/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('image_choice', 'Image Choice'), ('audio_choice', 'Audio Choice'), ('video_choice', 'Video Choice')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizhubapi.guest')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizhubapi.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizhubapi.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizhubapi.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizhubapi.answer')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('total_quizzes', models.IntegerField(default=0)),
                ('average_percentage', models.FloatField(default=0.0)),
                ('best_streak', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizhubapi.guest')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='quizhubapi.leaderboard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('leaderboard', 'user', 'guest')},
            },
        ),
    ]
